### ISSUE TITLE
caddy add-package show this module is not an official Caddy module

### ISSUE THREAD

**Issue by tom-temp** [caddyserver/transform-encoder#15]
I want to add this module to my caddy using `caddy add-package https://github.com/caddyserver/transform-encoder`.

However, it said
```
add-package: download failed: download failed: HTTP 400: https://github.com/caddyserver/transform-encoder is not a registered Caddy module package path
```

It seems that you have changed the name of this project in github, but did not set this up on `https://caddyserver.com/download`

**Comment by mholt** [comment]
You're right -- my bad! Just registered it under the new name.
