### ISSUE TITLE
logs are missing corresponding entries captured in default Caddy access.log

### ISSUE THREAD

**Issue by glenstewart** [caddyserver/transform-encoder#26]
Using Caddy 2.6.2, I see that many entries are missing from the Common and/or Combined log output, which are captured when I switch back to the normal access.log.

I am guessing something changed (lately) in Caddy, and the transform-encoder doesn't know how to handle it.

**Comment by francislavoie** [comment]
Please be more specific. Which logs? What do they look like before and after? Try to isolate it to individual requests.

**Comment by glenstewart** [comment]
For example, access.log will show this:

{"level":"debug","ts":"24/Nov/2022:16:11:45 +0000","logger":"http.log.error","msg":"{id=s4kv4f6v5} fileserver.(*FileServer).notFound (staticfiles.go:579): HTTP 404","request":{"remote_ip":"192.168.1.3","remote_port":"38556","proto":"HTTP/2.0","method":"GET","host":"welovegod.org:8443","uri":"/js/default.js","headers":{"Sec-Ch-Ua-Platform":["\"Linux\""],"Sec-Fetch-Site":["same-origin"],"Sec-Fetch-Mode":["no-cors"],"Cookie":[],"Sec-Gpc":["1"],"User-Agent":["Mozilla/5.0 (X11; U; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.5172.138 Safari/537.36"],"Accept-Encoding":["gzip, deflate, br"],"Referer":["https://welovegod.org:8443/recipes"],"Sec-Fetch-Dest":["script"],"Accept-Language":["en-US,en;q=0.9"],"Dnt":["1"],"Sec-Ch-Ua-Mobile":["?0"],"Accept":["*/*"],"Sec-Ch-Ua":["\"(Not(A:Brand\";v=\"99\", \"Chromium\";v=\"106\", \"Google Chrome\";v=\"106\""]},"tls":{"resumed":false,"version":772,"cipher_suite":4865,"proto":"h2","server_name":"welovegod.org"}},"duration":0.000078285,"status":404,"err_id":"s4kv4f6v5","err_trace":"fileserver.(*FileServer).notFound (staticfiles.go:579)"}

...but the site_combined.log  will show no entry.  I can tail -f site_combined.log and hit the server with good and bad requests, and only occasionally (in the first minutes after the server starts) will any logging happen - then it goes silent.

**Comment by francislavoie** [comment]
Those are `http.log.error`, i.e. not access logs. They're a different category of log message. This encoder isn't meant to handle these.

**Comment by mholt** [comment]
(Closing, unless there's something actionable here. If so, please post a config and instructions to minimally-reproduce the issue so we can look at fixing it. Thanks!)
