### ISSUE TITLE
time_local with transform-encoder plugin only shows amount of seconds in loggin

### ISSUE THREAD

**Issue by wazerstar** [caddyserver/transform-encoder#29]
Took latest caddy with latest transform-encoder and cloudflare in for windows x64

https://caddyserver.com/download?package=github.com%2Fcaddy-dns%2Fcloudflare&package=github.com%2Fcaddyserver%2Ftransform-encoder

Using caddyfile

```
log {
        format transform [{ts}] - User={user_id} - X-Forwarded-For={request>headers>X-Forwarded-For} - remote_ip={request>remote_ip} Country={request>headers>Cf-Ipcountry} {request>method} {request>headers>X-Forwarded-Proto} {request>host} {request>uri} {request>headers>Referer>[0]} {request>headers>User-Agent>[0]} - {request>proto} {status} {size} - {
		time_local
        }
```

Output in logs show this as date/time placeholder?
```
[1671100101.8262057]
[1671100113.9987721]

```

Reverting back to my old setup does the same thing with latest compile, what am I doing wrong?

```
log {
        format transform [{ts}] - User={user_id} - X-Forwarded-For={request>headers>X-Forwarded-For} - remote_ip={request>remote_ip} Country={request>headers>Cf-Ipcountry} {request>method} {request>headers>X-Forwarded-Proto} {request>host} {request>uri} {request>headers>Referer>[0]} {request>headers>User-Agent>[0]} - {request>proto} {status} {size} - {
		time_format "02/Jan/2006 15:04:05 -0700"
        }
```

**Comment by francislavoie** [comment]
`time_local` is not a format, it's just "which timezone to use". By default, UTC is used. `time_local` sets it to use your local system's configured timezone.

**Comment by wazerstar** [comment]
> `time_local` is not a format, it's just "which timezone to use". By default, UTC is used. `time_local` sets it to use your local system's configured timezone. Without a format, the default for times is to output "amount of seconds since the Unix epoch (Jan 1st 1970)"

Ah so I still have to use the same format I current use

This is correct?

```
log {
        format transform [{ts}] - User={user_id} - X-Forwarded-For={request>headers>X-Forwarded-For} - remote_ip={request>remote_ip} Country={request>headers>Cf-Ipcountry} {request>method} {request>headers>X-Forwarded-Proto} {request>host} {request>uri} {request>headers>Referer>[0]} {request>headers>User-Agent>[0]} - {request>proto} {status} {size} - {
		time_format "02/Jan/2006 15:04:05 -0700"
		time_local
        }
```

**Comment by wazerstar** [comment]
Does not work for me, same output I just want it to follow my transform custom output with time_local added, I dont see how else to make it work?

**Comment by francislavoie** [comment]
> Ah so I still have to use the same format I current use

Yes. All that option will do is shift the times over by your system's configured timezone, instead of UTC (i.e. same as GMT, +0:00). You still need to configure a format for the time for it to be output in the format you want.

**Comment by wazerstar** [comment]
> > Ah so I still have to use the same format I current use
> 
> Yes. All that option will do is shift the times over by your system's configured timezone, instead of UTC (i.e. same as GMT, +0:00). You still need to configure a format for the time for it to be output in the format you want.
> 
> I'm not clear on what problem you think there is. Please be more specific about what you've tried, the output you're seeing and what you expect to see.



I want to read clear and readable date and time, like it did previous but with my correct local time zone.

https://www.timeanddate.com/worldclock/denmark/copenhagen

I would like the date and time look something like this as of today [17-12-2022 15:38:17] which would be the other way around for some countries 12-17-2022 or just 17 December 2022


I tried another example to add what you did in https://github.com/caddyserver/caddy/pull/5108



```
log {
	format transform [{ts}] - User={user_id} - X-Forwarded-For={request>headers>X-Forwarded-For} - remote_ip={request>remote_ip} Country={request>headers>Cf-Ipcountry} {request>method} {request>headers>X-Forwarded-Proto} {request>host} {request>uri} {request>headers>Referer>[0]} {request>headers>User-Agent>[0]} - {request>proto} {status} {size} - {
		time_format wall_milli
		time_local
	}
```



The output was still shown as amount of seconds.


```
[1671287259.8469737] - User= - X-Forwarded-For=[""] - remote_ip= Country=[""] GET ["https"] - - -
```

**Comment by francislavoie** [comment]
Are you using the latest build of this plugin, from the master branch?

Can you show us what it looks like when you adapt your config to JSON with `caddy adapt --pretty`? It might be an issue with the Caddyfile support for this plugin.

**Comment by wazerstar** [comment]
> Are you using the latest build of this plugin, from the master branch?
> 
> Can you show us what it looks like when you adapt your config to JSON with `caddy adapt --pretty`? It might be an issue with the Caddyfile support for this plugin.

Copying it all in raw format on github simply would crash browser so I added all txt into txt file instead, github does not support .json extension either.


[output.txt](https://github.com/caddyserver/transform-encoder/files/10253108/output.txt)

**Comment by mohammed90** [comment]
Can you run `caddy list-modules --versions` and share the output? Ensure you're running the downloaded binary, of course.

**Comment by wazerstar** [comment]
> caddy list-modules --versions

Listed in console like this.

```
caddy.logging.encoders.formatted v0.0.0-20221214192817-b3b302b5455c
caddy.logging.encoders.transform v0.0.0-20221214192817-b3b302b5455c
dns.providers.cloudflare v0.0.0-20221129173028-ed330a80c094
```

**Comment by francislavoie** [comment]
I'm not seeing either of the time options in the JSON config, and your `list-modules` does show the latest commit, so I figure there's still a bug with the Caddyfile adapter of this plugin.

**Comment by mohammed90** [comment]
I'm very confused because it's working for me using both, a binary built with xcaddy and built from the caddy website. This Caddyfile:

```
{
	admin localhost:2999
}
localhost
file_server {
	root $HOME
}
log {
	format transform "[{ts}] {request>method} {request>host} {request>uri} {request>headers>User-Agent>[0]} - {request>proto} {status} {size} -" {
		time_format wall_milli
		time_local
	}
}
```

<summary>Adapts to this JSON: </summary>
<details>
```
{
	"admin": {
		"listen": "localhost:2999"
	},
	"logging": {
		"logs": {
			"default": {
				"exclude": [
					"http.log.access.log0"
				]
			},
			"log0": {
				"encoder": {
					"format": "transform",
					"template": "[{ts}] {request\u003emethod} {request\u003ehost} {request\u003euri} {request\u003eheaders\u003eUser-Agent\u003e[0]} - {request\u003eproto} {status} {size} -",
					"time_format": "wall_milli",
					"time_local": true
				},
				"include": [
					"http.log.access.log0"
				]
			}
		}
	},
	"apps": {
		"http": {
			"servers": {
				"srv0": {
					"listen": [
						":443"
					],
					"routes": [
						{
							"match": [
								{
									"host": [
										"localhost"
									]
								}
							],
							"handle": [
								{
									"handler": "subroute",
									"routes": [
										{
											"handle": [
												{
													"handler": "file_server",
													"hide": [
														"./Caddyfile"
													],
													"root": "$HOME"
												}
											]
										}
									]
								}
							],
							"terminal": true
						}
					],
					"logs": {
						"logger_names": {
							"localhost": "log0"
						}
					}
				}
			}
		}
	}
}
```
</details>

Which prints such log lines (correct local time):
```
[2022/12/19 02:19:25.516] GET localhost /favicon.ico Mozilla/5.0 (Windows NT 10.0; rv:108.0) Gecko/20100101 Firefox/108.0 - HTTP/2.0 404 0 -
```

@wazerstar, can you double-check you're running the correct executable?

**Comment by wazerstar** [comment]
> log {
> 	format transform "[{ts}] {request>method} {request>host} {request>uri} {request>headers>User-Agent>[0]} - {request>proto} {status} {size} -" {
> 		time_format wall_milli
> 		time_local
> 	}
> }

Hey I quickly checked your string compared to mine and the difference you got that I do not have is the " " between "[{ts}] and -"

So after latest changes this is extremely sensitive and cannot work without adding " " after format transform and before { 

?

**Comment by mohammed90** [comment]
> > log {
> > format transform "[{ts}] {request>method} {request>host} {request>uri} {request>headers>User-Agent>[0]} - {request>proto} {status} {size} -" {
> > time_format wall_milli
> > time_local
> > }
> > }
> 
> Hey I quickly checked your string compared to mine and the difference you got that I do not have is the " " between "[{ts}] and -"
> 
> I can confirm its working after adding double quote in beginning and the end.
> 
> So after latest changes this is extremely sensitive and cannot work without adding " " after format transform and before {
> 
> ?
> 
> Now how can I change the month and day in the output string
> 
> Current [2022/12/19 01:28:22.980]
> 
> I would like [2022/**19**/**12** 01:28:22.980]

Thanks for the clue! Not taking care of the case of missing quote marks was the issue. The tokenizer consider quoted arguments as a single token while unquoted args are multiple tokens. I missed taking care of that distinction. Try now :)

**Comment by francislavoie** [comment]
You want `year/day/month`? That's... extremely strange.

**Comment by wazerstar** [comment]
> You want `year/day/month`? That's... extremely strange. That means your logs can't be sorted by time, etc.
> 
> That said, glad this is figured out 👍

Hey Now I'm curious

Why would they not be sorted by time when you sort it after the day and then the time?

Yeah I'm glad we all got it fixed together all long :)

**Comment by francislavoie** [comment]
> Why would they not be sorted by time when you sort it after the day and then the time?

Because if you have days before months, then when the month rolls over from 05 to 06 let's say, the month is the number _after_ the day, so day 01 will technically sort higher than the month. You'd have all the logs from the 1st of each month first, then the logs from each 2nd of each month next, and so on.

This isn't a problem for append-only log streams, but if you later try to sort the logs for whatever reason, it won't be in a sensible order anymore.

The only sensible ways to do it IMO are d/m/y or y/m/d (because they're in order of hierarchy or reverse hierarchy), but y/m/d is better for any situation where you want to sort the data because of hierarchy; the number that changes the least should be to the left, and the number that changes the most is to the right. That's why seconds and milliseconds are last.
