### ISSUE TITLE
No data in formatted log file

### ISSUE THREAD

**Issue by pav67** [caddyserver/transform-encoder#32]
Hello,
My log file is full of formatted but empty lines like these : 
- - - [19/Mar/2023:13:20:06 +0000] "- - -" - - "-" "-"
- - - [19/Mar/2023:13:20:28 +0000] "- - -" - - "-" "-"
- - - [19/Mar/2023:13:20:44 +0000] "- - -" - - "-" "-"
- - - [19/Mar/2023:13:20:44 +0000] "- - -" - - "-" "-"

Here is my log config in /etc/caddy/Caddyfile (in the global config block) : 
log {
                format formatted `{request>remote_addr} - {request>user_id} [{ts}] "{request>method} {request>uri} {request>proto}" {status} {size} "{request>headers>Referer>[0]}" "{request>headers>User
-Agent>[0]}"` {
        time_format "02/Jan/2006:15:04:05 -0700"
                }
Is there something wrong with my config ?
Thank you!

**Comment by francislavoie** [comment]
It's `format transform`. See the README.

**Comment by mohammed90** [comment]
You're configuring non-access logs with an access-logger. Put the configuration within a site block so Caddy known to associate this logger with the access logs of the defined site. From the [docs](https://caddyserver.com/docs/caddyfile/options#log):

> The differs from the [log directive](https://caddyserver.com/docs/caddyfile/directives/log), which only configures HTTP request logging (also known as access logs).
